services:
  backend:
    build:
      context: ./backend
      target: ${ENV_MODE}
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/project/backend
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:16.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: